import { Venue } from '@/types/venue';

export const venues: Venue[] = [
  {
    id: '1',
    name: 'Bulawayo Rainbow Hotel',
    type: 'Hotel',
    description: 'Central hotel with recently updated accessibility ramps and wide elevators.',
    address: 'Corner 10th Avenue & Josiah Tongogara St',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80',
    rating: 4,
    features: {
      wheelchairAccessible: true,
      accessibleBathroom: true,
      stepFreeAccess: true,
      brailleSignage: false,
      signLanguageStaff: false,
      quietSpace: false,
      parking: true,
    },
    specs: {
      doorWidth: '95cm',
      rampGradient: '1:12 (Standard)',
      flooring: 'Short pile carpet',
    },
  },
  {
    id: '2',
    name: 'Natural History Museum',
    type: 'Museum',
    description: 'The largest museum in Zimbabwe. Ground floor is fully accessible, upper levels via elevator.',
    address: 'Leopold Takawira Avenue, Centenary Park',
    imageUrl: 'https://images.unsplash.com/photo-1544967082-d9d3fdd01a1d?auto=format&fit=crop&q=80',
    rating: 4.5,
    features: {
      wheelchairAccessible: true,
      accessibleBathroom: true,
      stepFreeAccess: true,
      brailleSignage: true,
      signLanguageStaff: false,
      quietSpace: true,
      parking: true,
    },
    specs: {
      doorWidth: '110cm',
      rampGradient: 'Flat Entry',
      flooring: 'Polished Concrete',
    },
  },
  {
    id: '3',
    name: 'The Cattleman Steakhouse',
    type: 'Restaurant',
    description: 'Popular grill house. Note: Entry has one small step, but portable ramp is available on request.',
    address: 'Lobengula St',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80',
    rating: 3,
    features: {
      wheelchairAccessible: true,
      accessibleBathroom: false,
      stepFreeAccess: false,
      brailleSignage: false,
      signLanguageStaff: true,
      quietSpace: false,
      parking: false,
    },
    specs: {
      doorWidth: '80cm',
      rampGradient: 'Portable Ramp',
      flooring: 'Tile',
    },
  },
];
